// Converted from test/universe/corpus/epsi-thesis.typ by scripts/convert-suite.ts — do not edit.
/* eslint-disable */
import {
  T,
  auto,
  blocks,
  define,
  dict,
  doc,
  figure,
  fr,
  horizon,
  image,
  importPackage,
  includeFile,
  inline,
  label,
  labelled,
  linebreak,
  link,
  m,
  parbreak,
  path,
  pct,
  pt,
  raw,
  ref,
  show,
  space,
  strong,
  sym,
  table,
  unsafeRaw,
} from '../../../src/index.ts'

export default () => {
  const project = define('project').pos('arg1', T.any).returns(T.any).external()
  return doc(
    importPackage('@preview/epsi-thesis:0.1.0', [project]),
    show(
      project(
        dict({
          title: 'Título Título Título Título Título Título Título Título Título Título Título Título',
          author: 'Nome do Autor',
          'degree-type': 'msc',
          'document-type': 'Dissertação de Mestrado',
          'degree-name': 'Mestrado em X',
          'school-id': 'EP',
          supervisors: ['Professor Doutor X', 'Professora Doutora Y', 'Professora Doutora Z', 'Professora Doutora W'],
          'supervisor-gender': 'M',
          year: 2026,
          month: 'maio',
          language: 'PT',
          'include-acknowledgements': true,
          'include-funding': true,
          'include-abstract-pt': true,
          'include-acronyms': true,
          'include-glossary': true,
          'include-bibliography': true,
          'bibliography-style': 'ieee',
          'bibliography-path': 'bibliography.bib',
          'acronyms-path': 'acronyms.yml',
          'glossary-path': 'glossary.yml',
          'copyright-content': blocks(
            inline(image(path('assets/copyright/CCBY.png'))),
            inline(strong(inline`CC BY`)),
            inline(link('https://creativecommons.org/licenses/by/4.0/')),
            inline(linebreak()),
            inline(image(path('assets/copyright/CCBYSA.png'))),
            inline(strong(inline`CC BY-SA`)),
            inline(link('https://creativecommons.org/licenses/by-sa/4.0/')),
            inline(linebreak()),
            inline(image(path('assets/copyright/CCBYND.png'))),
            inline(strong(inline`CC BY-ND`)),
            inline(link('https://creativecommons.org/licenses/by-nd/4.0/')),
            inline(linebreak()),
            inline(image(path('assets/copyright/CCBYNC.png'))),
            inline(strong(inline`CC BY-NC`)),
            inline(link('https://creativecommons.org/licenses/by-nc/4.0/')),
            inline(linebreak()),
            inline(image(path('assets/copyright/CCBYNCSA.png'))),
            inline(strong(inline`CC BY-NC-SA`)),
            inline(link('https://creativecommons.org/licenses/by-nc-sa/4.0/')),
            inline(linebreak()),
            inline(image(path('assets/copyright/CCBYNCND.png'))),
            inline(strong(inline`CC BY-NC-ND`)),
            inline(link('https://creativecommons.org/licenses/by-nc-nd/4.0/')),
          ),
          acknowledgements: inline`${space}Agradeço aos meus orientadores pelo apoio constante...${space}`,
          funding: inline`${space}Este trabalho foi financiado por...${space}`,
          'integrity-content': inline(space),
          'ai-tools-content': inline(space),
          'abstract-pt': inline`${space}Este é o texto do resumo em português. Pode ter vários parágrafos.${space}`,
          'keywords-pt': ['Portugal', 'Mundo'],
          'abstract-en': inline`${space}This is the abstract text in English. Multiple paragraphs allowed.${space}`,
          'keywords-en': ['Portugal', 'World'],
          body: blocks(
            m.heading(1, 'Demonstração de Funcionalidades (Guia Rápido)'),
            m.lines(
              m.heading(2, 'Inserir Imagens'),
              inline`Para inserir uma imagem, usamos a função ${raw('#figure')}. O Typst trata da numeração automática.`,
            ),
            inline(
              labelled(
                [
                  figure(
                    { caption: inline`Legenda da imagem explicativa.` },
                    image({ width: pct(80) }, path('images/example.png')),
                  ),
                  space,
                ],
                label('fig-exemplo'),
              ),
            ),
            inline`Como podes ver na ${ref(label('fig-exemplo'))}, a imagem fica centrada por padrão.`,
            m.lines(
              m.heading(2, 'Tabelas'),
              'As tabelas são muito intuitivas. Podes definir o número de colunas e o alinhamento.',
            ),
            inline(
              labelled(
                [
                  figure(
                    { caption: inline`Exemplo de uma tabela comparativa.` },
                    table(
                      { columns: [auto, fr(1), fr(1)], inset: pt(10), align: horizon },
                      inline(strong(inline`ID`)),
                      inline(strong(inline`Ferramenta`)),
                      inline(strong(inline`Utilidade`)),
                      inline`1`,
                      inline`Typst`,
                      inline`Escrita de relatórios`,
                      inline`2`,
                      inline`Python`,
                      inline`Análise de dados`,
                      inline`3`,
                      inline`Git`,
                      inline`Controlo de versões`,
                    ),
                  ),
                  space,
                ],
                label('tab-ferramentas'),
              ),
            ),
            m.lines(
              m.heading(2, 'Equações Matemáticas'),
              inline`O Typst usa uma sintaxe parecida com LaTeX, mas sem os comandos complexos. Usa-se o símbolo
${raw('$')}.`,
            ),
            inline`Equação na linha: ${unsafeRaw.math`E = m c^2`}.`,
            inline`Equação em bloco: ${unsafeRaw.math.block`sum_(k=1)^n k = (n(n+1)) / 2`}`,
            m.lines(
              m.heading(2, 'Listas e Blocos de Código'),
              'Podes criar listas numeradas e blocos de código com destaque de sintaxe:',
            ),
            m.enum(m.numbered(1, ['Primeiro passo']), m.numbered(2, ['Segundo passo'])),
            inline(raw({ block: true, lang: 'python' }, 'def saudacao(nome):\n    print(f"Olá, {nome}!")')),
            m.heading(1, 'Introdução'),
            'Este é o primeiro capítulo do relatório.',
            m.lines(
              'Os objetivos principais são:',
              m.list(
                m.item(['Objetivo 1: Estudar padrões de design', space, ref(label('gamma1994'))]),
                m.item(['Objetivo 2: Aplicar boas práticas de programação', space, ref(label('dijkstra1968'))]),
                m.item(['Objetivo 3: Utilizar tecnologias web modernas', space, ref(label('mozilla2024'))]),
              ),
            ),
            m.heading(1, 'Estado da Arte'),
            'Neste capítulo apresenta-se a revisão da literatura.',
            m.heading(1, 'Conclusões'),
            'Conclusões finais do trabalho.',
            parbreak(),
          ),
          appendix: blocks(includeFile('appendix.typ')),
        }),
      ),
    ),
  )
}
