// Converted from test/universe/corpus/ohdsi-symposium-submission.typ by scripts/convert-suite.ts — do not edit.
/* eslint-disable */
import {
  T,
  bibliography,
  define,
  doc,
  importPackage,
  inline,
  label,
  m,
  path,
  ref,
  show,
  space,
} from '../../../src/index.ts'

export default () => {
  const submission = define('submission')
    .pos('arg1', T.any)
    .named('affiliations', T.any, null)
    .named('authors', T.any, null)
    .named('title', T.any, null)
    .returns(T.any)
    .external()
  const referencesSection = define('references-section').pos('arg1', T.content).returns(T.any).external()
  return doc(
    importPackage('@preview/ohdsi-symposium-submission:0.1.0', [submission, referencesSection]),
    show((doc_2, ctx) =>
      submission(
        {
          title: 'OHDSI Symposium Submission Title',
          authors: [
            { name: 'FIRST AUTHOR', affiliations: ['1'] },
            { name: 'SECOND AUTHOR', affiliations: ['1', '2'] },
            { name: 'THIRD AUTHOR', affiliations: ['2'] },
          ],
          affiliations: [
            { id: '1', name: 'Department or Organization, City, Country' },
            { id: '2', name: 'Second Department or Organization, City, Country' },
          ],
        },
        doc_2,
      ),
    ),
    m.heading(1, 'Background'),
    inline`Use this section to summarize the scientific background, explain the gap your work addresses,
and clarify why the topic matters to the OHDSI community. This submission should describe unpublished
work at the time of submission, although preprints are acceptable. Cite relevant prior OHDSI
or domain work directly in the text. ${ref(label('hripcsak2015'))} ${ref(label('reps2018'))}`,
    inline`This brief report should stay between 200 and 1000 words, excluding references, authors, affiliations,
and optional figures or tables. Community resources can also be cited when useful. ${ref(label('ohdsi2024'))}`,
    m.heading(1, 'Methods'),
    'Describe the data source, cohort definition, study design, tooling, and analysis approach clearly enough for reviewers to understand what was done. If helpful, you may include up to three supporting figures or tables in the submission.',
    m.heading(1, 'Results'),
    'Summarize the main findings and emphasize the concrete evidence generated by the analysis, software demonstration, or implementation work. Use concise text and only include figures or tables when they materially support the results.',
    m.heading(1, 'Conclusions'),
    'Close with the main takeaway, the relevance for OHDSI collaborators, and the next step or expected impact of the work. References are recommended, with a practical target of no more than 15 citations.',
    inline(
      referencesSection(
        inline(space, bibliography({ title: null, style: 'vancouver-superscript' }, path('refs.bib')), space),
      ),
    ),
  )
}
