// Converted from test/suite/corpus/alignment-inv.typ by scripts/convert-suite.ts — do not edit.
/* eslint-disable */
import {
  T,
  add,
  bottom,
  center,
  define,
  doc,
  end,
  horizon,
  inline,
  left,
  right,
  space,
  start,
  top,
  unsafeRaw,
} from '../../../src/index.ts'

export default () => {
  const test = define('test').pos('arg1', T.any).pos('arg2', T.any).returns(T.any).external()
  return doc(
    inline(
      test(start.inv(), end),
      space,
      test(end.inv(), start),
      space,
      test(left.inv(), right),
      space,
      test(right.inv(), left),
      space,
      test(center.inv(), center),
      space,
      test(top.inv(), bottom),
      space,
      test(bottom.inv(), top),
      space,
      test(horizon.inv(), horizon),
      space,
      test(unsafeRaw.code<any>`(start + top).inv()`, add(end, bottom)),
      space,
      test(unsafeRaw.code<any>`(end + top).inv()`, add(start, bottom)),
      space,
      test(unsafeRaw.code<any>`(left + top).inv()`, add(right, bottom)),
      space,
      test(unsafeRaw.code<any>`(right + top).inv()`, add(left, bottom)),
      space,
      test(unsafeRaw.code<any>`(center + top).inv()`, add(center, bottom)),
      space,
      test(unsafeRaw.code<any>`(start + bottom).inv()`, add(end, top)),
      space,
      test(unsafeRaw.code<any>`(end + bottom).inv()`, add(start, top)),
      space,
      test(unsafeRaw.code<any>`(left + bottom).inv()`, add(right, top)),
      space,
      test(unsafeRaw.code<any>`(right + bottom).inv()`, add(left, top)),
      space,
      test(unsafeRaw.code<any>`(center + bottom).inv()`, add(center, top)),
      space,
      test(unsafeRaw.code<any>`(start + horizon).inv()`, add(end, horizon)),
      space,
      test(unsafeRaw.code<any>`(end + horizon).inv()`, add(start, horizon)),
      space,
      test(unsafeRaw.code<any>`(left + horizon).inv()`, add(right, horizon)),
      space,
      test(unsafeRaw.code<any>`(right + horizon).inv()`, add(left, horizon)),
      space,
      test(unsafeRaw.code<any>`(center + horizon).inv()`, add(center, horizon)),
      space,
      test(unsafeRaw.code<any>`(top + start).inv()`, add(end, bottom)),
      space,
      test(unsafeRaw.code<any>`(bottom + end).inv()`, add(start, top)),
      space,
      test(unsafeRaw.code<any>`(horizon + center).inv()`, add(center, horizon)),
    ),
  )
}
