// Converted from test/suite/corpus/color-conversion.typ by scripts/convert-suite.ts — do not edit.
/* eslint-disable */
import {
  T,
  cmyk,
  color,
  define,
  deg,
  doc,
  float,
  inline,
  luma,
  oklab,
  oklch,
  pct,
  rgb,
  space,
} from '../../../src/index.ts'

export default () => {
  const test = define('test').pos('arg1', T.any).pos('arg2', T.any).returns(T.any).external()
  const testRepr = define('test-repr').pos('arg1', T.any).pos('arg2', T.any).returns(T.any).external()
  return doc(
    inline(
      test(rgb(rgb(10, 20, 30)).space(), rgb),
      space,
      test(color.linearRgb(rgb(10, 20, 30)).space(), color.linearRgb),
      space,
      test(oklab(rgb(10, 20, 30)).space(), oklab),
      space,
      test(oklch(rgb(10, 20, 30)).space(), oklch),
      space,
      test(color.hsl(rgb(10, 20, 30)).space(), color.hsl),
      space,
      test(color.hsv(rgb(10, 20, 30)).space(), color.hsv),
      space,
      test(cmyk(rgb(10, 20, 30)).space(), cmyk),
      space,
      test(luma(rgb(10, 20, 30)).space(), luma),
    ),
    inline(
      test(rgb(color.linearRgb(10, 20, 30)).space(), rgb),
      space,
      test(color.linearRgb(color.linearRgb(10, 20, 30)).space(), color.linearRgb),
      space,
      test(oklab(color.linearRgb(10, 20, 30)).space(), oklab),
      space,
      test(oklch(color.linearRgb(10, 20, 30)).space(), oklch),
      space,
      test(color.hsl(color.linearRgb(10, 20, 30)).space(), color.hsl),
      space,
      test(color.hsv(color.linearRgb(10, 20, 30)).space(), color.hsv),
      space,
      test(cmyk(color.linearRgb(10, 20, 30)).space(), cmyk),
      space,
      test(luma(color.linearRgb(10, 20, 30)).space(), luma),
    ),
    inline(
      test(rgb(oklab(pct(10), pct(20), pct(30))).space(), rgb),
      space,
      test(color.linearRgb(oklab(pct(10), pct(20), pct(30))).space(), color.linearRgb),
      space,
      test(oklab(oklab(pct(10), pct(20), pct(30))).space(), oklab),
      space,
      test(oklch(oklab(pct(10), pct(20), pct(30))).space(), oklch),
      space,
      test(color.hsl(oklab(pct(10), pct(20), pct(30))).space(), color.hsl),
      space,
      test(color.hsv(oklab(pct(10), pct(20), pct(30))).space(), color.hsv),
      space,
      test(cmyk(oklab(pct(10), pct(20), pct(30))).space(), cmyk),
      space,
      test(luma(oklab(pct(10), pct(20), pct(30))).space(), luma),
    ),
    inline(
      test(rgb(oklch(pct(60), pct(40), deg(0))).space(), rgb),
      space,
      test(color.linearRgb(oklch(pct(60), pct(40), deg(0))).space(), color.linearRgb),
      space,
      test(oklab(oklch(pct(60), pct(40), deg(0))).space(), oklab),
      space,
      test(oklch(oklch(pct(60), pct(40), deg(0))).space(), oklch),
      space,
      test(color.hsl(oklch(pct(60), pct(40), deg(0))).space(), color.hsl),
      space,
      test(color.hsv(oklch(pct(60), pct(40), deg(0))).space(), color.hsv),
      space,
      test(cmyk(oklch(pct(60), pct(40), deg(0))).space(), cmyk),
      space,
      test(luma(oklch(pct(60), pct(40), deg(0))).space(), luma),
    ),
    inline(
      test(rgb(color.hsl(deg(10), pct(20), pct(30))).space(), rgb),
      space,
      test(color.linearRgb(color.hsl(deg(10), pct(20), pct(30))).space(), color.linearRgb),
      space,
      test(oklab(color.hsl(deg(10), pct(20), pct(30))).space(), oklab),
      space,
      test(oklch(color.hsl(deg(10), pct(20), pct(30))).space(), oklch),
      space,
      test(color.hsl(color.hsl(deg(10), pct(20), pct(30))).space(), color.hsl),
      space,
      test(color.hsv(color.hsl(deg(10), pct(20), pct(30))).space(), color.hsv),
      space,
      test(cmyk(color.hsl(deg(10), pct(20), pct(30))).space(), cmyk),
      space,
      test(luma(color.hsl(deg(10), pct(20), pct(30))).space(), luma),
    ),
    inline(
      test(rgb(color.hsv(deg(10), pct(20), pct(30))).space(), rgb),
      space,
      test(color.linearRgb(color.hsv(deg(10), pct(20), pct(30))).space(), color.linearRgb),
      space,
      test(oklab(color.hsv(deg(10), pct(20), pct(30))).space(), oklab),
      space,
      test(oklch(color.hsv(deg(10), pct(20), pct(30))).space(), oklch),
      space,
      test(color.hsl(color.hsv(deg(10), pct(20), pct(30))).space(), color.hsl),
      space,
      test(color.hsv(color.hsv(deg(10), pct(20), pct(30))).space(), color.hsv),
      space,
      test(cmyk(color.hsv(deg(10), pct(20), pct(30))).space(), cmyk),
      space,
      test(luma(color.hsv(deg(10), pct(20), pct(30))).space(), luma),
    ),
    inline(
      test(rgb(cmyk(pct(10), pct(20), pct(30), pct(40))).space(), rgb),
      space,
      test(color.linearRgb(cmyk(pct(10), pct(20), pct(30), pct(40))).space(), color.linearRgb),
      space,
      test(oklab(cmyk(pct(10), pct(20), pct(30), pct(40))).space(), oklab),
      space,
      test(oklch(cmyk(pct(10), pct(20), pct(30), pct(40))).space(), oklch),
      space,
      test(color.hsl(cmyk(pct(10), pct(20), pct(30), pct(40))).space(), color.hsl),
      space,
      test(color.hsv(cmyk(pct(10), pct(20), pct(30), pct(40))).space(), color.hsv),
      space,
      test(cmyk(cmyk(pct(10), pct(20), pct(30), pct(40))).space(), cmyk),
      space,
      test(luma(cmyk(pct(10), pct(20), pct(30), pct(40))).space(), luma),
    ),
    inline(
      test(rgb(luma(pct(10))).space(), rgb),
      space,
      test(color.linearRgb(luma(pct(10))).space(), color.linearRgb),
      space,
      test(oklab(luma(pct(10))).space(), oklab),
      space,
      test(oklch(luma(pct(10))).space(), oklch),
      space,
      test(color.hsl(luma(pct(10))).space(), color.hsl),
      space,
      test(color.hsv(luma(pct(10))).space(), color.hsv),
      space,
      test(cmyk(luma(pct(10))).space(), cmyk),
      space,
      test(luma(luma(pct(10))).space(), luma),
    ),
    inline(
      test(rgb(1, 2, 3).toHex(), '#010203'),
      space,
      test(rgb(1, 2, 3, 4).toHex(), '#01020304'),
      space,
      test(luma(40).toHex(), '#282828'),
      space,
      testRepr(cmyk(pct(4), pct(5), pct(6), pct(7)).toHex(), '#e2dcda'),
      space,
      testRepr(rgb(cmyk(pct(4), pct(5), pct(6), pct(7))), rgb(226, 220, 218)),
      space,
      testRepr(rgb(luma(pct(40))), rgb(pct(40), pct(40), pct(40))),
      space,
      testRepr(cmyk(luma(40)), cmyk(pct(63.24), pct(57.33), pct(56.49), pct(75.88))),
      space,
      testRepr(cmyk(rgb(1, 2, 3)), cmyk(pct(66.67), pct(33.33), pct(0), pct(98.82))),
      space,
      testRepr(luma(rgb(1, 2, 3)), luma(pct(0.73))),
      space,
      testRepr(color.hsl(luma(40)), color.hsl(deg(0), pct(0), pct(15.69))),
      space,
      testRepr(color.hsv(luma(40)), color.hsv(deg(0), pct(0), pct(15.69))),
      space,
      testRepr(color.linearRgb(luma(40)), color.linearRgb(pct(2.12), pct(2.12), pct(2.12))),
      space,
      testRepr(color.linearRgb(rgb(1, 2, 3)), color.linearRgb(pct(0.03), pct(0.06), pct(0.09))),
      space,
      testRepr(color.hsl(rgb(1, 2, 3)), color.hsl(deg(-150), pct(50), pct(0.78))),
      space,
      testRepr(color.hsv(rgb(1, 2, 3)), color.hsv(deg(-150), pct(66.67), pct(1.18))),
      space,
      testRepr(oklab(luma(40)), oklab(pct(27.68), float(0), float(0), pct(100))),
      space,
      testRepr(oklab(rgb(1, 2, 3)), oklab(pct(8.23), -0.004, -0.007, pct(100))),
      space,
      testRepr(oklch(oklab(pct(40), 0.2, 0.2)), oklch(pct(40), 0.283, deg(45), pct(100))),
      space,
      testRepr(oklch(luma(40)), oklch(pct(27.68), float(0), deg(72.49), pct(100))),
      space,
      testRepr(oklch(rgb(1, 2, 3)), oklch(pct(8.23), 0.008, deg(240.75), pct(100))),
    ),
  )
}
