// Converted from test/suite/corpus/decimal-display.typ by scripts/convert-suite.ts — do not edit.
/* eslint-disable */
import { auto, decimal, doc, inline, linebreak, m, minus, page, set, space } from '../../../src/index.ts'

export default () => {
  return doc(
    m.lines(
      set(page, { width: auto }),
      inline(
        decimal('12.0'),
        space,
        linebreak(),
        space,
        decimal('3.14'),
        space,
        linebreak(),
        space,
        decimal('1234567890.0'),
        space,
        linebreak(),
        space,
        decimal('0123456789.0'),
        space,
        linebreak(),
        space,
        decimal('0.0'),
        space,
        linebreak(),
        space,
        decimal('-0.0'),
        space,
        linebreak(),
        space,
        decimal('-1.0'),
        space,
        linebreak(),
        space,
        decimal('-9876543210.0'),
        space,
        linebreak(),
        space,
        decimal('-0987654321.0'),
        space,
        linebreak(),
        space,
        decimal('-3.14'),
        space,
        linebreak(),
        space,
        decimal('-3.9191919191919191919191919195'),
        space,
        linebreak(),
        space,
        decimal('5.0000000000'),
        space,
        linebreak(),
        space,
        minus(decimal('4.0'), decimal('8.0')),
      ),
    ),
  )
}
