// Converted from test/suite/corpus/float-display.typ by scripts/convert-suite.ts — do not edit.
/* eslint-disable */
import { data, doc, float, inline, linebreak, minus, neg, space } from '../../../src/index.ts'

export default () => {
  return doc(
    inline(
      data(float(12)),
      space,
      linebreak(),
      space,
      data(3.14),
      space,
      linebreak(),
      space,
      data(float(1234567890)),
      space,
      linebreak(),
      space,
      data(float(123456789)),
      space,
      linebreak(),
      space,
      data(float(0)),
      space,
      linebreak(),
      space,
      data(float('-0.0')),
      space,
      linebreak(),
      space,
      data(float(-1)),
      space,
      linebreak(),
      space,
      data(float(-9876543210)),
      space,
      linebreak(),
      space,
      data(float(-987654321)),
      space,
      linebreak(),
      space,
      data(-3.14),
      space,
      linebreak(),
      space,
      minus(float(4), float(8)),
      space,
      linebreak(),
      space,
      float.inf,
      space,
      linebreak(),
      space,
      neg(float.inf),
      space,
      linebreak(),
      space,
      float.nan,
    ),
  )
}
