// Converted from test/suite/corpus/ops-compare.typ by scripts/convert-suite.ts — do not edit.
/* eslint-disable */
import { T, define, doc, inline, space, unsafeRaw } from '../../../src/index.ts'

export default () => {
  const test = define('test').pos('arg1', T.any).pos('arg2', T.any).returns(T.any).external()
  return doc(
    inline(
      test(unsafeRaw.code<any>`13 * 3 < 14 * 4`, true),
      space,
      test(unsafeRaw.code<any>`5 < 10`, true),
      space,
      test(unsafeRaw.code<any>`5 > 5`, false),
      space,
      test(unsafeRaw.code<any>`5 <= 5`, true),
      space,
      test(unsafeRaw.code<any>`5 <= 4`, false),
      space,
      test(unsafeRaw.code<any>`45deg < 1rad`, true),
      space,
      test(unsafeRaw.code<any>`10% < 20%`, true),
      space,
      test(unsafeRaw.code<any>`50% < 40% + 0pt`, false),
      space,
      test(unsafeRaw.code<any>`40% + 0pt < 50% + 0pt`, true),
      space,
      test(unsafeRaw.code<any>`1em < 2em`, true),
      space,
      test(unsafeRaw.code<any>`(0, 1, 2, 4) < (0, 1, 2, 5)`, true),
      space,
      test(unsafeRaw.code<any>`(0, 1, 2, 4) < (0, 1, 2, 3)`, false),
      space,
      test(unsafeRaw.code<any>`(0, 1, 2, 3.3) > (0, 1, 2, 4)`, false),
      space,
      test(unsafeRaw.code<any>`(0, 1, 2) < (0, 1, 2, 3)`, true),
      space,
      test(unsafeRaw.code<any>`(0, 1, "b") > (0, 1, "a", 3)`, true),
      space,
      test(unsafeRaw.code<any>`(0, 1.1, 3) >= (0, 1.1, 3)`, true),
      space,
      test(
        unsafeRaw.code<any>`(0, 1, datetime(day: 1, month: 12, year: 2023)) <= (0, 1, datetime(day: 1, month: 12, year: 2023), 3)`,
        true,
      ),
      space,
      test(unsafeRaw.code<any>`("a", 23, 40, "b") > ("a", 23, 40)`, true),
      space,
      test(unsafeRaw.code<any>`() <= ()`, true),
      space,
      test(unsafeRaw.code<any>`() >= ()`, true),
      space,
      test(unsafeRaw.code<any>`() <= (1,)`, true),
      space,
      test(unsafeRaw.code<any>`(1,) <= ()`, false),
      space,
      test(unsafeRaw.code<any>`decimal("123.0000000000000000000000001") > decimal("123.0")`, true),
      space,
      test(unsafeRaw.code<any>`decimal("123.5") < decimal("122.444")`, false),
      space,
      test(unsafeRaw.code<any>`decimal("459.9999999999999999999999999") < 460`, true),
      space,
      test(unsafeRaw.code<any>`decimal("128.50") > 460`, false),
    ),
  )
}
